### DISCUSSION TITLE
Check HA status

### DISCUSSION THREAD

**Discussion by acbrigan** [citrix/citrix-adc-ansible-modules#425] [Q&A] [answered]
I'm looking for a way to check the HA status of a node and only run certain tasks if the node is primary.  Is there already a way to do this?

**Comment by sumanth-lingappa** [comment, marked as answer]
The `netscaler.adc` ansible collection is yet to have `_info` modules. This is being tracked by #296 and #372.

However, the previous `citrix.adc` module had [`citrix_adc_nitro_info`](https://galaxy.ansible.com/ui/repo/published/citrix/adc/content/module/citrix_adc_nitro_info/) module. You can use it till the same is supported in `netscaler.adc`

Example playbook

```yaml
- hosts: localhost
  gather_facts: False
  tasks:
    - name: Retrieve info
      delegate_to: localhost
      citrix.adc.citrix_adc_nitro_info:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no
        endpoint: hanode
        args:
          id: 0
      register: result

    - name: Print HA State
      debug:
        msg: "{{ result['nitro_info'][0]['state'] }}"
```
