### DISCUSSION TITLE
Disable graceful - Too few arguments

### DISCUSSION THREAD

**Discussion by drhirn** [citrix/citrix-adc-ansible-modules#518] [Q&A]
Trying to disable a service gracefully but always getting the error `Too few arguments`.

Playbook-Task:
```
    - name: Disable Service
      delegate_to: localhost
      netscaler.adc.service:
        nitro_auth_token: "{{ login_result.sessionid }}"
        nsip: 192.0.2.1
        state: disabled
        name: EXAMPLE_01-HTTP
        graceful: "YES"
        delay: "0"
```

Error:
```
"TRACE: EXIT: common.update_resource() returned (False, \"ERROR: update_resource FAILED; status_code: 400; Reason:{'errorcode': 1094, 'message': 'Too few arguments', 'severity': 'ERROR'}\")"
```

It's working when removing `graceful`.
Can't find out, which argument is missing? Can you please give me any hints?

```
Red Hat Enterprise Linux 8.10
python version = 3.12.8
ansible [core 2.16.3]
netscaler.adc 2.8.0
```
