### ISSUE TITLE
No SNI support in citrix_adc_cs_vserver

### ISSUE THREAD

**Issue by efenex** [citrix/citrix-adc-ansible-modules#112]
It is possible to have a CS vserver with multiple certificates in Netscaler, but this is not possible when using these ansible modules. The "ssl_certkey" module is a string rather than a list. Worse yet, if you use "netscaler_nitro_request" to manually bind multiple ssl keys, the module crashes with the following stacktrace:

      File "/tmp/ansible_netscaler_cs_vserver_payload_a0id3_lp/ansible_netscaler_cs_vserver_payload.zip/ansible/modules/network/netscaler/netscaler_cs_vserver.py", line 1252, in main
      File "/tmp/ansible_netscaler_cs_vserver_payload_a0id3_lp/ansible_netscaler_cs_vserver_payload.zip/ansible/modules/network/netscaler/netscaler_cs_vserver.py", line 810, in ssl_certkey_bindings_sync
      File "ansible/netscaler/venv/lib/python3.8/site-packages/nssrc/com/citrix/netscaler/nitro/resource/config/ssl/sslvserver_sslcertkey_binding.py", line 254, in delete
        raise e
      File "ansible/netscaler/venv/lib/python3.8/site-packages/nssrc/com/citrix/netscaler/nitro/resource/config/ssl/sslvserver_sslcertkey_binding.py", line 241, in delete
        return deleteresource.delete_resource(client)
      File "ansible/netscaler/venv/lib/python3.8/site-packages/nssrc/com/citrix/netscaler/nitro/resource/base/base_resource.py", line 226, in delete_resource
        raise e
      File "ansible/netscaler/venv/lib/python3.8/site-packages/nssrc/com/citrix/netscaler/nitro/resource/base/base_resource.py", line 222, in delete_resource
        str_ = nitro_util.object_to_string_withoutquotes(self)
      File "ansible/netscaler/venv/lib/python3.8/site-packages/nssrc/com/citrix/netscaler/nitro/util/nitro_util.py", line 120, in object_to_string_withoutquotes
        raise e
      File "ansible/netscaler/venv/lib/python3.8/site-packages/nssrc/com/citrix/netscaler/nitro/util/nitro_util.py", line 110, in object_to_string_withoutquotes
        str_ = str_ + v

      File "/tmp/ansible_netscaler_cs_vserver_payload_a0id3_lp/ansible_netscaler_cs_vserver_payload.zip/ansible/modules/network/netscaler/netscaler_cs_vserver.py", line 1252, in main
      File "/tmp/ansible_netscaler_cs_vserver_payload_a0id3_lp/ansible_netscaler_cs_vserver_payload.zip/ansible/modules/network/netscaler/netscaler_cs_vserver.py", line 810, in ssl_certkey_bindings_sync
      File "/home/rdesmet/git/stuart/ansible/netscaler/venv/lib/python3.8/site-packages/nssrc/com/citrix/netscaler/nitro/resource/config/ssl/sslvserver_sslcertkey_binding.py", line 254, in delete
        raise e
      File "/home/rdesmet/git/stuart/ansible/netscaler/venv/lib/python3.8/site-packages/nssrc/com/citrix/netscaler/nitro/resource/config/ssl/sslvserver_sslcertkey_binding.py", line 241, in delete
        return deleteresource.delete_resource(client)
      File "/home/rdesmet/git/stuart/ansible/netscaler/venv/lib/python3.8/site-packages/nssrc/com/citrix/netscaler/nitro/resource/base/base_resource.py", line 226, in delete_resource
        raise e
      File "/home/rdesmet/git/stuart/ansible/netscaler/venv/lib/python3.8/site-packages/nssrc/com/citrix/netscaler/nitro/resource/base/base_resource.py", line 222, in delete_resource
        str_ = nitro_util.object_to_string_withoutquotes(self)
      File "/home/rdesmet/git/stuart/ansible/netscaler/venv/lib/python3.8/site-packages/nssrc/com/citrix/netscaler/nitro/util/nitro_util.py", line 120, in object_to_string_withoutquotes
        raise e
      File "/home/rdesmet/git/stuart/ansible/netscaler/venv/lib/python3.8/site-packages/nssrc/com/citrix/netscaler/nitro/util/nitro_util.py", line 110, in object_to_string_withoutquotes
        str_ = str_ + v
    TypeError: can only concatenate str (not "bool") to str

**Comment by ppieprzycki** [comment]
Also please check PR https://github.com/citrix/citrix-adc-ansible-modules/pull/119

**Comment by giorgos-nikolopoulos** [comment]
I have update the workflows dictionary found [here](https://github.com/citrix/citrix-adc-ansible-modules/blob/master/deps/workflows.yaml) to include `sslvserver_sslcertkey_binding` resource.

I suggest to create the necessary sni certificate bindings with the citrix_adc_nitro_resource module using a playbook like the following:

```yaml
- hosts: citrix_adc
  gather_facts: no
  collections:
    - citrix.adc
  vars_files:
    - workflows.yaml

  tasks:
    - name: Add sni certrificate
      delegate_to: localhost
      citrix_adc_nitro_resource:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no
        state: present

        workflow: "{{ workflow.sslvserver_sslcertkey_binding }}"


        resource:
          vservername: test-ssl
          certkeyname: snicert1
          ca: false
          snicert: true
```
