### ISSUE TITLE
Deprecated netscaler-ansible docker image

### ISSUE THREAD

**Issue by matt6697** [citrix/citrix-adc-ansible-modules#116]
Netscaler Ansible image available on Docker Hub is outdated (deprecated ansible version, difficult to use for other purposes than testing citrix adc configuration).

I worked on an updated docker image in a forked citrix-adc-ansible-module https://github.com/virtualdesktopdevops/citrix-adc-ansible-modules/blob/feature/docker-container/Dockerfile.

```
FROM alpine:3.10

ENV ANSIBLE_VERSION=2.9.2

# Install Python3 and Ansible
RUN set -xe \
    && echo "****** Install system dependencies ******" \
    && apk add --no-cache --progress python3 openssl ca-certificates git openssh sshpass \
	  && apk --update add --virtual build-dependencies python3-dev libffi-dev openssl-dev build-base \
	  && echo "****** Install ansible and python dependencies ******" \
    && pip3 install --upgrade pip \
	  && pip3 install ansible==${ANSIBLE_VERSION} \
    && echo "****** Remove unused system librabies ******" \
	  && apk del build-dependencies \
	  && rm -rf /var/cache/apk/*

# Install Citrix ADC Ansible modules
RUN wget -O /tmp/citrix-adc-ansible-modules.tar.gz https://github.com/citrix/citrix-adc-ansible-modules/archive/v1.8.tar.gz \
    && cd /tmp \
    && tar -zxvf citrix-adc-ansible-modules.tar.gz \
    && pip3 install citrix-adc-ansible-modules-1.8/deps/nitro-python-1.0_kamet.tar.gz \
    && python3 citrix-adc-ansible-modules-1.8/install.py \
    && rm -rf citrix-adc-ansible-modules-1.8 citrix-adc-ansible-modules.tar.gz \
    && mkdir /pwd

WORKDIR /pwd

CMD ["ansible-playbook", "--version"]
```

As you are not able to accept external pull request at the moment, Wwould you like to integrate this Dockerfile in your repository and publish an updated docker image ? If not, do I have authorization to push the updated image from my forked repository to virtualdesktopdevops/citrix-adc-ansible-modules Dockerhub repository ?

**Comment by matt6697** [comment]
The https://hub.docker.com/r/virtualdesktopdevops/citrix-adc-ansible-modules image embedding the new Citrix ADC & ADM Ansible collections has been published on dockerhub.


Create an Ansible inventory file with the Citrix ADC nsip, nitro_user, nitro_password parameters :
```
[citrix_adc]
172.25.249.241 nsip=172.25.249.241:9443 nitro_user=nsroot nitro_pass=nsroot validate_certs=no
```
Create an Ansible playbook enbedding Citrix ADC configurations. Samples and documentation are provided on https://github.com/citrix/citrix-adc-ansible-modules :

```
---

- hosts: citrix_adc
  gather_facts: false
  collections:
    - citrix.adc

  tasks:
    - name: lb vserver
      delegate_to: localhost
      citrix_adc_lb_vserver:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no


        name: lb-vserver-1
        servicetype: HTTP
        ipv46: 6.92.2.2
        port: 80

    - name: cs action
      delegate_to: localhost
      citrix_adc_cs_action:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no

        name: action1
        targetlbvserver: lb-vserver-1
```
Run ansible-playbook using citrix-adc-ansible-modules docker image to deploy configuration :

```
docker run --rm -v $(pwd):/pwd citrix-adc-ansible-modules:latest ansible-playbook -i inventory.txt samples/cs_action.yaml 
```
