### ISSUE TITLE
Updating HTML responder page

### ISSUE THREAD

**Issue by l3ender** [citrix/citrix-adc-ansible-modules#120]
Is there an example that could point me how to update an HTML responder page?

https://developer-docs.citrix.com/projects/netscaler-nitro-api/en/11.1/configuration/responder/responderhtmlpage/responderhtmlpage/

Can this be done with this module, or do I need to use the URI module as shown in [uri-nitro-api-calls.yaml](https://github.com/citrix/citrix-adc-ansible-modules/blob/fed898d7a73fadcc4023237b8b7dc85f90327789/samples/nitro_request/uri-nitro-api-calls.yaml)?

**Comment by l3ender** [comment]
I was able to accomplish this with the `citrix_adc_nitro_request` module.

```yml
---
- name: Updates the Netscaler HTML responder page content.
  hosts: all
  connection: local
  gather_facts: no
  vars:
    input_filename: "filename_in_repo"
    input_file_contents: "{{ lookup('file', '{{ input_filename }}') }}"
    responder_filename: "filename_on_netscaler"
    responder_directory: "/var/download/responder"

  tasks:
  - name: Delete existing file on Netscaler
    citrix_adc_nitro_request:
      nsip: "{{ nsip }}"
      nitro_protocol: "https"
      nitro_user: "{{ nitro_user }}"
      nitro_pass: "{{ nitro_pass }}"
      operation: delete_by_args
      resource: systemfile/{{ responder_filename }}
      args:
        filelocation: "{{ responder_directory | replace('/','%2F') }}"
      expected_nitro_errorcode: [0, 3441]

  - name: Copy new file to Netscaler
    citrix_adc_nitro_request:
      nsip: "{{ nsip }}"
      nitro_protocol: "https"
      nitro_user: "{{ nitro_user }}"
      nitro_pass: "{{ nitro_pass }}"
      operation: add
      resource: systemfile
      attributes:
        filename: "{{ responder_filename }}"
        filelocation: "{{ responder_directory }}"
        filecontent: "{{ input_file_contents | b64encode }}"

  - name: Reload content on Netscaler
    citrix_adc_nitro_request:
      nsip: "{{ nsip }}"
      nitro_protocol: "https"
      nitro_user: "{{ nitro_user }}"
      nitro_pass: "{{ nitro_pass }}"
      operation: action
      action: update
      resource: responderhtmlpage
      attributes:
        name: "{{ responder_filename }}"
```

It can run like follows:
```
ansible-playbook update_netscaler.yml -i localhost, -e "nsip=1.2.3.4" -e "nitro_user=abc" -e "nitro_pass=123"
```
