### ISSUE TITLE
Problem removing ssl cipher binding

### ISSUE THREAD

**Issue by brilong** [citrix/citrix-adc-ansible-modules#129]
I am able to associate a customer cipher list using the following task without any issue:
```
    - name: Netscaler Enforce | SSL vserver SSL cipher binding
      delegate_to: localhost
      citrix_adc_nitro_request:
        nsip: "{{ netscaler_host_ip }}"
        nitro_user: "{{ netscaler_nitro_user }}"
        nitro_pass: "{{ netscaler_nitro_password }}"
        nitro_protocol: "{{ netscaler_nitro_protocol }}"
        validate_certs: "{{ netscaler_validate_certs }}"
        operation: add
        resource: sslvserver_sslcipher_binding
        name: "{{ netscaler_virtual_endpoint }}"
        attributes:
          vservername: "{{ netscaler_virtual_endpoint }}"
          ciphername: "{{ netscaler_sslvserver_cipher }}"
```

However, this leaves the DEFAULT cipher also tied to the ssl vserver.  I am unable to remove the DEFAULT cipher from the ssl vserver and I have tried two different methods and resources (sslcipher_sslvserver_binding and sslvserver_sslcipher_binding):
```
    - name: Netscaler Enforce | SSL vserver SSL cipher unbinding
      delegate_to: localhost
      citrix_adc_nitro_request:
        nsip: "{{ netscaler_host_ip }}"
        nitro_user: "{{ netscaler_nitro_user }}"
        nitro_pass: "{{ netscaler_nitro_password }}"
        nitro_protocol: "{{ netscaler_nitro_protocol }}"
        validate_certs: "{{ netscaler_validate_certs }}"
        operation: delete
        resource: sslcipher_sslvserver_binding
        name: "{{ netscaler_virtual_endpoint }}"
        attributes:
          vservername: "{{ netscaler_virtual_endpoint }}"
          ciphergroupname: "{{ item }}"
          cipheroperation: "REM"
      with_items: "{{ existing_wrong_sslcipher_binding }}"

```
OR
```
    - name: Netscaler Enforce | SSL vserver SSL cipher unbinding
      delegate_to: localhost
      citrix_adc_nitro_request:
        nsip: "{{ netscaler_host_ip }}"
        nitro_user: "{{ netscaler_nitro_user }}"
        nitro_pass: "{{ netscaler_nitro_password }}"
        nitro_protocol: "{{ netscaler_nitro_protocol }}"
        validate_certs: "{{ netscaler_validate_certs }}"
        operation: delete
        resource: sslvserver_sslcipher_binding
        name: "{{ netscaler_virtual_endpoint }}"
        attributes:
          vservername: "{{ netscaler_virtual_endpoint }}"
          ciphergroupname: "{{ item }}"
      with_items: "{{ existing_wrong_sslcipher_binding }}"
```

The sanitized output from both tries is below:

Using sslvserver_sslcipher_binding:
----------------------------------

```
TASK [netscaler : Netscaler Enforce | List of sslciphersuite_binding] **********
task path: /etc/ansible/roles/netscaler/tasks/netscaler_enforce.yml:138
Monday 29 June 2020  15:26:06 +0000 (0:00:00.069)       0:01:00.227 ***********
ok: [my-hostname] => {
    "ansible_facts": {
        "existing_sslcipher_binding": [
            "DEFAULT",
            "myteam-strong-ciphers"
        ]
    },
    "changed": false
}

TASK [netscaler : Netscaler Enforce | List of sslciphersuite_binding not matching netscaler_sslvserver_cipher] ***
task path: /etc/ansible/roles/netscaler/tasks/netscaler_enforce.yml:142
Monday 29 June 2020  15:26:06 +0000 (0:00:00.064)       0:01:00.291 ***********
ok: [my-hostname] => {
    "ansible_facts": {
        "existing_wrong_sslcipher_binding": [
            "DEFAULT"
        ]
    },
    "changed": false
}

TASK [netscaler : Netscaler Enforce | SSL vserver SSL cipher binding] **********
task path: /etc/ansible/roles/netscaler/tasks/netscaler_enforce.yml:146
Monday 29 June 2020  15:26:06 +0000 (0:00:00.071)       0:01:00.363 ***********
skipping: [my-hostname] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}

TASK [netscaler : Netscaler Enforce | SSL vserver SSL cipher unbinding] ********
task path: /etc/ansible/roles/netscaler/tasks/netscaler_enforce.yml:162
Monday 29 June 2020  15:26:06 +0000 (0:00:00.062)       0:01:00.425 ***********
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/netscaler/citrix_adc_nitro_request.py
Pipelining is enabled.
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: myansible
<localhost> EXEC /bin/sh -c '/usr/bin/python2 && sleep 0'
failed: [my-hostname -> localhost] (item=DEFAULT) => {
    "ansible_loop_var": "item",
    "changed": false,
    "headers": {
        "Content-Type": "application/json",
        "X-NITRO-PASS": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
        "X-NITRO-USER": "mynsroot"
    },
    "http_response_body": "{ \"errorcode\": 1095, \"message\": \"Required argument missing [policyName, eccCurveName]\", \"severity\": \"ERROR\" }",
    "http_response_data": {
        "cache-control": "no-store, no-cache, must-revalidate, post-check=0, pre-check=0",
        "connection": "close",
        "content-length": "109",
        "content-type": "application/json; charset=utf-8",
        "date": "Mon, 29 Jun 2020 22:18:20 GMT",
        "expires": "Thu, 19 Nov 1981 08:52:00 GMT",
        "msg": "HTTP Error 400: Bad Request",
        "pragma": "no-cache",
        "server": "Apache",
        "status": 400,
        "url": "https://10.1.2.4/nitro/v1/config/sslvserver_sslcipher_binding/my-vserver",
        "x-frame-options": "SAMEORIGIN",
        "x-xss-protection": "1; mode=block"
    },
    "invocation": {
        "module_args": {
            "action": null,
            "args": null,
            "attributes": {
                "ciphername": "DEFAULT",
                "vservername": "my-vserver"
            },
            "expected_nitro_errorcode": [
                0
            ],
            "filter": null,
            "instance_id": null,
            "instance_ip": null,
            "instance_name": null,
            "name": "my-vserver",
            "nitro_auth_token": null,
            "nitro_pass": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "nitro_protocol": "https",
            "nitro_user": "mynsroot",
            "nsip": "10.1.2.4",
            "operation": "delete",
            "resource": "sslvserver_sslcipher_binding",
            "timeout": 45,
            "validate_certs": false
        }
    },
    "item": "DEFAULT",
    "msg": "NITRO Failure",
    "nitro_errorcode": 1095,
    "nitro_message": "Required argument missing [policyName, eccCurveName]",
    "nitro_severity": "ERROR"
}
```

Different task instead (sslcipher_sslvserver_binding):
-----------------------

```
TASK [netscaler : Netscaler Enforce | SSL vserver SSL cipher unbinding] ********
task path: /etc/ansible/roles/netscaler/tasks/netscaler_enforce.yml:150
Monday 29 June 2020  15:36:35 +0000 (0:00:00.062)       0:00:58.630 ***********
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/netscaler/citrix_adc_nitro_request.py
Pipelining is enabled.
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: myansible
<localhost> EXEC /bin/sh -c '/usr/bin/python2 && sleep 0'
failed: [my-hostname -> localhost] (item=DEFAULT) => {
    "ansible_loop_var": "item",
    "changed": false,
    "headers": {
        "Content-Type": "application/json",
        "X-NITRO-PASS": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
        "X-NITRO-USER": "mynsroot"
    },
    "http_response_body": "{ \"errorcode\": 1091, \"message\": \"Required argument value missing\", \"severity\": \"ERROR\" }",
    "http_response_data": {
        "cache-control": "no-store, no-cache, must-revalidate, post-check=0, pre-check=0",
        "connection": "close",
        "content-length": "88",
        "content-type": "application/json; charset=utf-8",
        "date": "Mon, 29 Jun 2020 22:28:48 GMT",
        "expires": "Thu, 19 Nov 1981 08:52:00 GMT",
        "msg": "HTTP Error 400: Bad Request",
        "pragma": "no-cache",
        "server": "Apache",
        "status": 400,
        "url": "https://10.1.2.4/nitro/v1/config/sslcipher_sslvserver_binding/my-vserver",
        "x-frame-options": "SAMEORIGIN",
        "x-xss-protection": "1; mode=block"
    },
    "invocation": {
        "module_args": {
            "action": null,
            "args": null,
            "attributes": {
                "ciphergroupname": "DEFAULT",
                "cipheroperation": "REM",
                "vservername": "my-vserver"
            },
            "expected_nitro_errorcode": [
                0
            ],
            "filter": null,
            "instance_id": null,
            "instance_ip": null,
            "instance_name": null,
            "name": "my-vserver",
            "nitro_auth_token": null,
            "nitro_pass": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "nitro_protocol": "https",
            "nitro_user": "mynsroot",
            "nsip": "10.1.2.4",
            "operation": "delete",
            "resource": "sslcipher_sslvserver_binding",
            "timeout": 45,
            "validate_certs": false
        }
    },
    "item": "DEFAULT",
    "msg": "NITRO Failure",
    "nitro_errorcode": 1091,
    "nitro_message": "Required argument value missing",
    "nitro_severity": "ERROR"
}
```

Why does the first try say "Required argument missing [policyName, eccCurveName]"?  These two arguments are not documented in the sslvserver_sslcipher_binding resource.  What is the missing argument in the second try?

Thank you for any assistance you can provide.

**Comment by scarroll451** [comment]
Brian, have you found a solution for this issue?

FYI, I have just opened requests to add modules to create custom cipher lists and ssl profiles, by the way. Would rather have that than go the citrix_adc_nitro_request route. Had you implemented those on your own as well? Thanks!

**Comment by brilong** [comment]
@scarroll451, I have written an Ansible role using mostly Nitro REST API calls to handle the SSL ciphersuite creation, binding, unbinding, etc.  I have done it for both the service group (backend) and the virtual server (frontend).  I was tired of dealing with limited Ansible module support for the Citrix Netscaler SSL ciphers so I decided to use straight REST API calls.

**Comment by scarroll451** [comment]
Thanks. It's a shame to have us all reinvent the wheel, but perhaps a good exercise at the same time. I am opening RFEs for this and several others using our acct manager - we will see what happens. Thanks for the response!

**Comment by giorgos-nikolopoulos** [comment]
You need to use the `delete_by_args` operation with the `citrix_adc_nitro_request` module to delete the cipher.

See below for example:

```yaml
- hosts: citrix_adc

  vars:
    max_clients: 5
  gather_facts: False
  collections:
    - citrix.adc

  tasks:
    - name: Setup binding
      delegate_to: localhost
      citrix_adc_nitro_request:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"

        validate_certs: no

        operation: delete_by_args
        resource: sslvserver_sslcipher_binding
        args:
          ciphername: DEFAULT
          vservername: test_ssl
```
