### ISSUE TITLE
High availability support

### ISSUE THREAD

**Issue by l3ender** [citrix/citrix-adc-ansible-modules#130]
Do the modules support Netscaler/ADC instances that are deployed in high availability (HA)? If playbooks are run targeting the secondary node, do modules detect this and automatically run commands against the primary node instead? Or should I target playbooks against both nodes?

Please advise. Thanks!

**Comment by l3ender** [comment]
I was able to get this working but doing a Nitro request to load HA (hanode) status, and then conditionally setting the hostname that would be used for future tasks.

```yml
---
- name: Detects primary Netscaler node and runs operation on it.
  hosts: all
  connection: local
  gather_facts: no
  vars:
    ns_hostname_primary: "{{ ns_input_host }}-ns01.mycompany.local"
    ns_hostname_secondary: "{{ ns_input_host }}-ns02.mycompany.local"

  tasks:
  - name: Determine primary HA node
    citrix_adc_nitro_request:
      nsip: "{{ ns_hostname_primary }}"
      nitro_protocol: "https"
      nitro_user: "{{ nitro_user }}"
      nitro_pass: "{{ nitro_pass }}"
      operation: get
      resource: hanode
      name: "0" # own node
    register: ha_status

  - name: "Set hostname based on HA status"
    set_fact:
      ns_hostname: "{{ ns_hostname_primary if ha_status.nitro_object[0].state == 'Primary' else ns_hostname_secondary }}"

  - name: "Display hostname that will be used"
    debug: msg="{{ ns_hostname }}"

  - name: Run operation on primary Netscaler
    citrix_adc_nitro_request:
      nsip: "{{ ns_hostname }}"
      nitro_protocol: "https"
      nitro_user: "{{ nitro_user }}"
      nitro_pass: "{{ nitro_pass }}"
      operation: ...
```

This works for our environment because our primary/secondary hostnames in HA are named like:
* datacenter1-public-ns01.mycompany.local
* datacenter1-public-ns02.mycompany.local

Usage of the playbook is as follows:
```
ansible-playbook playbook.yml -i localhost, -e "ns_input_host=datacenter1-public" -e "nitro_user=aaa" -e "nitro_pass=123"
```
