### ISSUE TITLE
missing ability to set sslProfile on lb vserver

### ISSUE THREAD

**Issue by scarroll451** [citrix/citrix-adc-ansible-modules#156]
I have reviewed and searched the citrix_adc_lb_vserver.py module, and I do not see any parameter that indicates the ability to set an ssl profile on a type SSL lb vserver. Is this missing from the documentation, or from the module? Thank you. We use custom ssl profiles on all SSL VIPs for security (the default ssl profile is not secure).

**Comment by vadharm** [comment]
Included the requested feature in our plan. Will keep you posted.

**Comment by giorgos-nikolopoulos** [comment]
You can bind a sslprofile to a sslvserver with the use of the `citrix_adc_nitro_resource` module.

See the example below.

```yaml
- hosts: citrix_adc

  gather_facts: False
  vars_files:
    - ../deps/workflows.yaml
  collections:
    - citrix.adc

  tasks:

      # sslvsever should already exist
    - name: bind profile to sslvserver
      delegate_to: localhost
      citrix_adc_nitro_resource:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no

        # sslvserver cannot be deleted through this endpoint by setting state: absent
        # delete the corresponding lb or cs vserver
        state: present

        workflow: "{{ workflow.sslvserver }}"

        resource:
          vservername: test_ssl
          sslprofile: test_ssl_profile
```
