### ISSUE TITLE
Not able to bind responder policy to lb vserver (citrix_adc_lb_vserver.py module)

### ISSUE THREAD

**Issue by scarroll451** [citrix/citrix-adc-ansible-modules#157]
I have reviewed and searched the citrix_adc_lb_vserver.py module, and I do not see any parameter that indicates the ability to bind a responder policy to an lb vserver - just appfw policies.. Is this missing from the documentation, or from the module itself? Thank you.

**Comment by LizK-TTS** [comment]
Just a comment on this... I have been able to add Responder and Rewrite policies to load balancing and content switching virtual servers using the appfw_policybindings parameter. Not sure if this was the intended use but it does work.

For example:
In my ansible task:
    appfw_policybindings: "{{ item.value.policybindings | default(omit) }}"

In my vars:
    policybindings:
      - policyname: pol_responder_example_binded_at_request
        priority: '100'
        gotopriorityexpression: END
        bindpoint: REQUEST
      - policyname: pol_rewrite_example_binded_at_response
        priority: '105'
        gotopriorityexpression: '120'
        bindpoint: RESPONSE

**Comment by giorgos-nikolopoulos** [comment]
You can use `citrix_adc_nitro_resource` to do the bindings using the `lbvserver_responderpolicy_binding` endpoint.

Here is a sample playbook that does that

```yaml
- hosts: citrix_adc

  gather_facts: False
  vars_files:
    - workflows.yaml
  collections:
    - citrix.adc

  tasks:
    - name: Setup responder policy binding
      delegate_to: localhost
      citrix_adc_nitro_resource:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no

        state: present

        workflow: "{{ workflow.lbvserver_responderpolicy_binding }}"

        resource:
          name: test_ssl
          policyname: Top_URL
          priority: "10"
```
