### ISSUE TITLE
Need module to create custom cipher list

### ISSUE THREAD

**Issue by scarroll451** [citrix/citrix-adc-ansible-modules#158]
I don't see this ability in any of the 30 or so ADC modules. This is an example of a command-line version of what we are looking to do:

add ssl cipher CIPHER-STANDARD-2019-07_cg
bind ssl cipher CIPHER-STANDARD-2019-07_cg -cipherName TLS1.2-ECDHE-RSA-AES256-GCM-SHA384 -cipherPriority 1
bind ssl cipher CIPHER-STANDARD-2019-07_cg -cipherName TLS1.2-ECDHE-RSA-AES128-GCM-SHA256 -cipherPriority 2
bind ssl cipher CIPHER-STANDARD-2019-07_cg -cipherName TLS1.2-ECDHE-RSA-AES-128-SHA256 -cipherPriority 3

Could this be added please? See related request on creating custom SSL profile (which will use/bind to a custom cipher list)

**Comment by vadharm** [comment]
Included the requested feature in our plan. Will keep you posted.

**Comment by giorgos-nikolopoulos** [comment]
#171 Added the modules needed for this use case.

Here is an example playbook.

```yaml
- hosts: citrix_adc

  gather_facts: False
  vars_files:
    - workflows.yaml
  collections:
    - citrix.adc

  tasks:
    - name: Setup cipher
      delegate_to: localhost
      citrix_adc_sslcipher:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"

        validate_certs: no
        state: present

        ciphergroupname: test_cipher

    - name: Setup cipher binding
      delegate_to: localhost
      citrix_adc_sslcipher_sslciphersuite_binding:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"

        validate_certs: no
        state: present

        ciphergroupname: test_cipher
        ciphername: TLS1.2-ECDHE-RSA-AES256-GCM-SHA384
        cipherpriority: "2"

    - name: Setup cipher binding
      delegate_to: localhost
      citrix_adc_sslcipher_sslciphersuite_binding:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"

        validate_certs: no
        state: present

        ciphergroupname: test_cipher
        ciphername: SSL3-EXP-ADH-DES-CBC-SHA
        cipherpriority: "4"

```
