### ISSUE TITLE
Need module to create ssl profile (and then the means to bind it to an SSL vserver in the lb/cs modules!)

### ISSUE THREAD

**Issue by scarroll451** [citrix/citrix-adc-ansible-modules#159]
I don't see the ability to add an SSL profile. Could this be added? Example (please make note of options/parameters and the lb vserver binding:

add ssl profile STANDARD-SSL_prof -sessReuse ENABLED -sessTimeout 120 -tls1 DISABLED -tls11 DISABLED -denySSLReneg NONSECURE
bind ssl profile STANDARD-SSL_prof -cipherName AWESOME-CIPHER-STANDARD_cg -cipherPriority 2
unbind ssl profile STANDARD-SSL_prof -cipherName DEFAULT

and then to bind to an SSL vserver:
set ssl vserver AWESOME_lb -sslProfile STANDARD-SSL_prof
save c

**Comment by LizK-TTS** [comment]
I would also appreciate this feature.

**Comment by vadharm** [comment]
Included the requested feature in our plan. Will keep you posted.

**Comment by giorgos-nikolopoulos** [comment]
#171 added the needed modules to implement this use case.

Here is an example

```yaml
- hosts: citrix_adc

  gather_facts: False
  vars_files:
    - workflows.yaml
  collections:
    - citrix.adc

  tasks:
    - name: Setup SSL profile
      delegate_to: localhost
      citrix_adc_nitro_resource:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no

        state: present

        workflow: "{{ workflow.sslprofile }}"

        resource:
          name: test_ssl_profile
          sessreuse: ENABLED
          sesstimeout: !!str 120
          tls1: DISABLED
          tls11: DISABLED
          denysslreneg: NONSECURE

    - name: Setup binding
      delegate_to: localhost
      citrix_adc_sslprofile_sslcipher_binding:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"

        validate_certs: no
        state: present

        name: test_ssl_profile
        ciphername: DTLS_FIPS
        cipherpriority: "5"

    - name: Setup binding
      delegate_to: localhost
      citrix_adc_sslprofile_sslcipher_binding:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"

        validate_certs: no
        state: present

        name: test_ssl_profile
        ciphername: TLS1.3-AES128-GCM-SHA256
        cipherpriority: "10"

    - name: Remove default binding
      delegate_to: localhost
      citrix_adc_sslprofile_sslcipher_binding:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"

        validate_certs: no
        state: absent

        name: test_ssl_profile
        ciphername: DEFAULT

      # sslvsever should already exist
    - name: bind profile to sslvserver
      delegate_to: localhost
      citrix_adc_nitro_resource:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no

        # sslvserver cannot be deleted through this endpoint by setting state: absent
        # delete the corresponding lb or cs vserver
        state: present

        workflow: "{{ workflow.sslvserver }}"

        resource:
          vservername: test_ssl
          sslprofile: test_ssl_profile
```
