### ISSUE TITLE
SSL Certificate Deployment Idempotency Issue

### ISSUE THREAD

**Issue by jfmainville** [citrix/citrix-adc-ansible-modules#181]
I'm currently encountering an intermittent idempotency issue with the SSL certificate deployment Python module (citrix_adc_ssl_certkey.py). Here's the Ansible task that I'm using to deploy the required SSL configuration: 
```
- name: deploy the SSL certificate
  delegate_to: localhost
  collections:
    - citrix.adc
  citrix_adc_ssl_certkey:
    nitro_user: "user123"
    nitro_pass: "pass123"
    nsip: "citrix-adc.test.com"
    certkey: "mycert"
    cert: "mycert.pfx"
    expirymonitor: enabled
    notificationperiod: "30"
    inform: "PFX"
    password: true
    passplain: "12345"
    validate_certs: no
```
When I run this task the first time, the SSL configuration is deployed successfully (changed) and other execution of the playbook during the same day works properly and the task is idempotent (ok). But, if I try to run the same task the next day, I get the following error message: 
```
fatal: [citrix-adc.test.com]: FAILED! => {"changed": false, "loglines": ["Applying actions for state present", "Checking if key exists", "certkey is mycert", "Checking if configured key is identical"], "msg": "Cannot update immutable attributes ['passplain', 'password']"}`
```
I troubleshooted the issue by adding additional log entries under the `key_identical` function and I can confirm that it returns False for some reason and it then fails here in the code (citrix_adc_ssl_certkey.py): 
```
elif not key_identical(client, module, sslcertkey_proxy):
  # Check if we try to change value of immutable attributes
  immutables_changed = get_immutables_intersection(sslcertkey_proxy, diff_list(client, module, sslcertkey_proxy).keys())
  # The immutables_changed variable returns ['passplain', 'password'] and I get the error below
  if immutables_changed != []:
      module.fail_json(
          msg='Cannot update immutable attributes %s' % (immutables_changed,),
          diff=diff_list(client, module, sslcertkey_proxy),
          **module_result
      )
```
Based on the investigation I completed so far, it looks like the idempotency breaks after certain period of time and the SSL certificate deployment Python module can't handle this unexpected change in configuration for some reason.

**Comment by vadharm** [comment]
Team will triage and get back to you.

**Comment by jfmainville** [comment]
To give an update, I tried to deploy the same SSL certificate, but using the PEM format which seems to be the most common deployment scenario by executing the following Ansible task and I got the same exact error message with this approach as well (see initial comment for the details): 
```
- name: deploy the SSL certificate
  delegate_to: localhost
  collections:
    - citrix.adc
  citrix_adc_ssl_certkey:
    nitro_user: "user123"
    nitro_pass: "pass123"
    nsip: "citrix-adc.test.com"
    certkey: "mycert"
    cert: "mycert.crt"
    key: "mycert.pem"
    expirymonitor: enabled
    notificationperiod: "30"
    inform: "PEM"
    password: true
    passplain: "12345"
    validate_certs: no
```
