### ISSUE TITLE
Support for partitions on Citrix ADC modules

### ISSUE THREAD

**Issue by gusmb** [citrix/citrix-adc-ansible-modules#198]
## Feature Request

Currently it is only possible to configure resources on the default partition, except for the `citrix.adc.nitro_request` module.  This issue is to request support for partitions in all network modules, which already work in an idempotent way and make configuration much more convenient and descriptive.
In my use case, I use different partitions on the Netscaler and the default partition is not used for load balancing services.

 ## Data model proposal

Add attribute `partition` to each network module, and support for authentication token, in order to be able  to target partitions for configuration.

Example:

```yaml
 - name: Set service 1
      delegate_to: localhost
      citrix_adc_service:
        nsip: "{{ nsip }}"
        nitro_token: "{{ nitro_token }}"
        validate_certs: "{{ validate_certs }}"
        partition: "{{ partition}}"
        state: present

        name: service-http-1
        servicetype: HTTP
        ipaddress: 10.78.0.1
        port: 80
```

Where `nitro_token` could be obtained by performing a login operation using the `nitro_request` module and saving the session token as an ansible fact to be passed to the network modules.

If `partition` is specified,  the module would perform a "switch partition" operation before pushing the  configs. Otherwise, the configuration would be pushed to the current partition for the given authentication token. This could be useful to switch partitions with the network modules and apply configurations in a flexible way.
