### ISSUE TITLE
citrix_adc_cs_vserver - Update module so it allows multiple SNI certificates bindings

### ISSUE THREAD

**Issue by Sarcasm0naut** [citrix/citrix-adc-ansible-modules#214]
The module already calls the sslvserver_sslcertkey_binding endpoint and performs comparisons over the response.
Could we kindly have this module updated so it supports passing multiple certificates to be bound, both by default and with SNI enabled?

**Comment by giorgos-nikolopoulos** [comment]
The `sslvserver_sslcertkey_binding` endpoint is implemented by the nitro_resource module.

I believe something like the following playbook would work for you use case
```yaml
- hosts: citrix_adc

  gather_facts: False
  vars_files:
    - ../../deps/workflows.yaml
  collections:
    - citrix.adc

  tasks:
    - name: Setup nitro resource
      delegate_to: localhost
      citrix_adc_nitro_resource:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no

        state: present

        workflow: "{{ workflow.sslvserver_sslcertkey_binding }}"

        resource:
          vservername: my_cs_vserver
          certkeyname: my_ssl_cert
          snicert: true
```
