### ISSUE TITLE
citrix_adc_lb_vserver - rule parameter missing

### ISSUE THREAD

**Issue by cwegener** [citrix/citrix-adc-ansible-modules#90]
The `rule` parameter for the lbvserver API entitiy is not available in the citrix_adc_lb_vserver Ansible module.

Only the `resrule` parameter is available.

This prevents the usage of persistencetype: *RULE*

**Comment by cwegener** [comment]
**Update**:
Having had a read of the citrix_adc_lb_vserver module, not even the `resrule` parameter is present. The `resrule` parameter is only mentioned in the module documentation but actually not implemented as a paramter either.

**Comment by giorgos-nikolopoulos** [comment]
This is a valid issue.

The reason these two attributes are not in the module's options is that the module makes the assumption that when an object is retrieved, even for values that are not set in the module arguments, the NITRO API returns every attribute of the specified object.
In most cases this is true. Even unset attributes are returned with default values.

This is useful for the module to assess the equality of the playbook configuration and the actual object attributes and decide if an update is necessary.

The `resrule` and `rule` options are not returned unless explicitly set on the object.
When the modules were written this situation was not addressed.

The fix for this would require to introduce handling for attributes with this particular behavior.

We will keep track of this issue and fix it in the future.

**Comment by giorgos-nikolopoulos** [comment]
We recently added the `citrix_adc_nitro_resource` module.

Have a look at its documentation [here](https://netscaler-ansible.readthedocs.io/en/latest/generic_modules/nitro_resource.html)

Perhaps you can use a playbook similar to the following to create a lb vserver with the rule parameter defined.

```yaml
- hosts: citrix_adc

  gather_facts: False
  vars_files:
    - workflows.yaml

  tasks:
    - name: Setup nitro resource lb vserver
      delegate_to: localhost
      citrix_adc_nitro_resource:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        state: present

        workflow: "{{ workflow.lbvserver }}"

        resource:
          name: lb-vserver-1
          servicetype: HTTP
          ipv46: 6.93.3.3
          port: 80
          rule: "some expression here"

```
