### ISSUE TITLE
add authentication ldapAction and loginSchema

### ISSUE THREAD

**Issue by felipe1982** [citrix/citrix-adc-ansible-modules#93]
How can I use this module to run commands similar to:

```shell
add authentication ldapAction sideOnPremNSG_LDAP_ACTION_SAM -serverIP 192.168.2.2 -serverPort 636 -ldapBase "dc=wde,dc=side,dc=com,dc=au" -ldapBindDn svc.nsldapdev@wde.side.com -ldapBindDnPassword 939e0250a9b275187b4b7cfa566fd4ceeded01ef34e2c0f9e7714bfdabb34a6b -encrypted -encryptmethod ENCMTHD_3 -ldapLoginName sAMAccountName -groupAttrName memberOf -subAttributeName cn -secType SSL
add authentication ldapPolicy sideOnPremNSG_LDAP_POLICY_SAM ns_true sideOnPremNSG_LDAP_ACTION_SAM

```
```shell
add authentication loginSchema lschema_dual_factor_secureID -authenticationSchema "/nsconfig/loginschema/DualAuth.xml"
add authentication loginSchemaPolicy lschema_dual_factor_secureID_pol -rule True -action lschema_dual_factor_secureID
add authentication loginSchemaPolicy lschema_dual_factor_receiver_pol -rule "http.REQ.HEADER(\"User-Agent\").CONTAINS(\"Receiver\")" -action lschema_dual_factor_secureID
bind authentication vserver VS_Connect_MFA_AAA -policy lschema_dual_factor_secureID_mfa_pol -priority 120 -gotoPriorityExpression END

```
```
add authentication radiusPolicy SecureID_Receiver_Policy "REQ.HTTP.HEADER User-Agent CONTAINS CitrixReceiver" SecureID_LB_Server
bind authentication vserver VS_Connect_MFA_AAA -policy RSASecureID_Receiver_Policy -priority 100 -nextFactor LDAP_sf_connect_receiver_pl2 -gotoPriorityExpression NEXT

```

**Comment by giorgos-nikolopoulos** [comment]
Since we do not have dedicated modules for these resources you will need to use the generic `citrix_adc_nitro_request` module to do these configurations.

Each nscli command usually translates to one NITRO object that needs to be created with the same attribute values as the command has options.
This is pretty straightforward since NITRO object names and attributes are generated in large part from the nscli definition files.

So to give an example for the first command
```shell
add authentication ldapAction sideOnPremNSG_LDAP_ACTION_SAM -serverIP 192.168.2.2 -serverPort 636 -ldapBase "dc=wde,dc=side,dc=com,dc=au" -ldapBindDn svc.nsldapdev@wde.side.com -ldapBindDnPassword 939e0250a9b275187b4b7cfa566fd4ceeded01ef34e2c0f9e7714bfdabb34a6b -encrypted -encryptmethod ENCMTHD_3 -ldapLoginName sAMAccountName -groupAttrName memberOf -subAttributeName cn -secType SSL
```

Would be translated to the following `citrix_adc_nitro_request` task

```
    - name: Add authentication ldap action
      delegate_to: localhost
      citrix_adc_nitro_request:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"

        operation: add

        resource: authenticationldapaction
        attributes:
          name: sideOnPremNSG_LDAP_ACTION_SAM 
          serverip: 192.168.2.2 
          serverport: 636
          ldapbase: "dc=wde,dc=side,dc=com,dc=au" 
          ldapbinddn: svc.nsldapdev@wde.side.com 
          ldapbinddnpassword: 939e0250a9b275187b4b7cfa566fd4ceeded01ef34e2c0f9e7714bfdabb34a6b 
          ldaploginname: sAMAccountName 
          groupattrname: memberOf 
          subattributename: cn
          sectype: SSL

```

Interestingly I could not find attributes to correspond to the `-encrypted` and `-encryptmethod` options, neither does the nscli definition contain these option. Nevertheless the command is correctly run in ADC 12.1.

If the omission of these two attributes makes the configuration not work correctly please follow up so I dig a little deeper into this. 

For the rest of the commands you just need to identify the correct NITRO object and do the same.
For bind commands there are special binding NITRO objects.

For your commands I think the following list of NITRO objects would do the job.

* [authenticationldapaction](https://developer-docs.citrix.com/projects/citrix-adc-nitro-api-reference/en/latest/configuration/authentication/authenticationldapaction/authenticationldapaction/)
* [authenticationldappolicy](https://developer-docs.citrix.com/projects/citrix-adc-nitro-api-reference/en/latest/configuration/authentication/authenticationldappolicy/authenticationldappolicy/)
* [authenticationloginschema](https://developer-docs.citrix.com/projects/citrix-adc-nitro-api-reference/en/latest/configuration/authentication/authenticationloginschema/authenticationloginschema/)
* [authenticationloginschemapolicy](https://developer-docs.citrix.com/projects/citrix-adc-nitro-api-reference/en/latest/configuration/authentication/authenticationloginschemapolicy/authenticationloginschemapolicy/)
* [authenticationvserver_authenticationloginschemapolicy_binding](https://developer-docs.citrix.com/projects/citrix-adc-nitro-api-reference/en/latest/configuration/authentication/authenticationvserver_authenticationloginschemapolicy_binding/authenticationvserver_authenticationloginschemapolicy_binding/)
* [authenticationradiuspolicy](https://developer-docs.citrix.com/projects/citrix-adc-nitro-api-reference/en/latest/configuration/authentication/authenticationradiuspolicy/authenticationradiuspolicy/)

As for the last bind command the correct object depends on the type of the policy being bound.

You will need to use on of the `authenticationvserver_*_binding` objects found [here](https://developer-docs.citrix.com/projects/citrix-adc-nitro-api-reference/en/latest/configuration/authentication/authentication/) that corresponds to the policy type.
